export enum MBGuildFeature {
    HEMOMANCER = 'HEMOMANCER',
    HMMMM = 'HMMMM',
    SPELLTABLE_TRIGGER = 'SPELLTABLE_TRIGGER',
    SONG_OF_THE_DAY = 'SONG_OF_THE_DAY',
    BETS = 'BETS',
    HALL_OF_FAME = 'HALL_OF_FAME',
    KERMIT_MONTH = 'KERMIT_MONTH'
}
